version: '2'
services:
    stretchcms-app:
        image: stretchcms
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://stretchcms-mysql:3306/stretchcms?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    stretchcms-mysql:
        extends:
            file: mysql.yml
            service: stretchcms-mysql
